"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-29 08:40:40.081429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_app',
    sa.Column('app_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='应用主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='应用名称'),
    sa.Column('icon', sa.String(length=500), nullable=True, comment='应用图标'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='应用描述'),
    sa.Column('app_type', sa.String(length=50), nullable=True, comment='应用类型/分类'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='状态: 0发布 1草稿'),
    sa.Column('config', sa.Text(), nullable=True, comment='应用配置JSON(prompt/绑定工具知识库/参数等)'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门ID'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('app_id'),
    comment='AI应用表'
    )
    op.create_index(op.f('ix_ai_app_tenant_id'), 'ai_app', ['tenant_id'], unique=False)
    op.create_table('ai_chat_config',
    sa.Column('chat_config_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='默认温度'),
    sa.Column('add_history_to_context', sa.CHAR(length=1), server_default='0', nullable=True, comment='是否添加历史记录(0是, 1否)'),
    sa.Column('num_history_runs', sa.Integer(), nullable=True, comment='历史记录条数'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
    sa.Column('metrics_default_visible', sa.CHAR(length=1), server_default='0', nullable=True, comment='默认显示指标(0是, 1否)'),
    sa.Column('vision_enabled', sa.CHAR(length=1), server_default='1', nullable=True, comment='是否开启视觉(0是, 1否)'),
    sa.Column('image_max_size_mb', sa.Integer(), nullable=True, comment='图片最大大小(MB)'),
    sa.Column('mcp_tool_ids', sa.String(length=500), nullable=True, comment='启用的MCP工具ID(逗号分隔)'),
    sa.Column('agent_app_ids', sa.String(length=500), nullable=True, comment='引用的应用agent ID(逗号分隔,多agent协作)'),
    sa.Column('enable_memory', sa.CHAR(length=1), server_default='1', nullable=True, comment='是否开启长期记忆(0是, 1否)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('chat_config_id'),
    sa.UniqueConstraint('user_id'),
    comment='AI对话配置表'
    )
    op.create_index(op.f('ix_ai_chat_config_tenant_id'), 'ai_chat_config', ['tenant_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('model_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='模型主键'),
    sa.Column('model_code', sa.String(length=100), nullable=False, comment='模型编码'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='模型名称'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='提供商'),
    sa.Column('model_sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('api_key', sa.String(length=255), nullable=True, comment='API Key'),
    sa.Column('base_url', sa.String(length=255), nullable=True, comment='Base URL'),
    sa.Column('model_type', sa.String(length=50), nullable=True, comment='模型类型'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大输出token'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='默认温度'),
    sa.Column('support_reasoning', sa.CHAR(length=1), server_default='N', nullable=True, comment='是否支持推理'),
    sa.Column('support_images', sa.CHAR(length=1), server_default='N', nullable=True, comment='是否支持图片'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='模型状态'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门ID'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('model_id'),
    comment='AI模型表'
    )
    op.create_index(op.f('ix_ai_models_tenant_id'), 'ai_models', ['tenant_id'], unique=False)
    op.create_table('ai_tool',
    sa.Column('tool_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='工具主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='工具代码(唯一标识)'),
    sa.Column('tool_type', sa.String(length=50), server_default='mcp', nullable=False, comment='工具类型: mcp/builtin'),
    sa.Column('description', sa.Text(), nullable=True, comment='工具描述'),
    sa.Column('args', sa.Text(), nullable=True, comment='工具配置JSON'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='状态: 0启用 1停用'),
    sa.Column('built_in', sa.CHAR(length=1), server_default='0', nullable=True, comment='是否内置: 1是(不可删/改code) 0否'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门ID'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('tool_id'),
    comment='AI工具表'
    )
    op.create_index(op.f('ix_ai_tool_tenant_id'), 'ai_tool', ['tenant_id'], unique=False)
    op.create_table('alert_record',
    sa.Column('alert_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='告警主键'),
    sa.Column('strategy_id', sa.BigInteger(), nullable=True, comment='告警策略id'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='告警标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='告警内容'),
    sa.Column('level', sa.Integer(), server_default='0', nullable=True, comment='告警等级'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=True, comment='告警状态(0未处理 1已处理)'),
    sa.Column('biz', sa.String(length=50), nullable=True, comment='告警业务(scheduler等)'),
    sa.Column('source', sa.String(length=200), nullable=True, comment='告警对象(任务名/实例等)'),
    sa.Column('metric', sa.String(length=100), nullable=True, comment='告警指标(task_fail/task_timeout等)'),
    sa.Column('tags', sa.Text(), nullable=True, comment='告警标签(JSON,含instance_id/worker/retries等)'),
    sa.Column('ext_params', sa.Text(), nullable=True, comment='额外参数(JSON)'),
    sa.Column('recover_time', sa.DateTime(), nullable=True, comment='恢复时间'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('alert_id'),
    comment='告警记录表'
    )
    op.create_index(op.f('ix_alert_record_tenant_id'), 'alert_record', ['tenant_id'], unique=False)
    op.create_table('alert_strategy',
    sa.Column('strategy_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='策略主键'),
    sa.Column('strategy_name', sa.String(length=200), nullable=False, comment='策略名称'),
    sa.Column('biz', sa.String(length=50), server_default='scheduler', nullable=True, comment='业务类型(scheduler等)'),
    sa.Column('trigger_conf', sa.Text(), nullable=True, comment='触发条件(JSON,含告警等级level等)'),
    sa.Column('forward_conf', sa.Text(), nullable=True, comment='转发渠道配置(JSON数组)'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态(1启用 0停用)'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注信息'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('strategy_id'),
    comment='告警策略表'
    )
    op.create_index(op.f('ix_alert_strategy_tenant_id'), 'alert_strategy', ['tenant_id'], unique=False)
    op.create_table('api_token',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=200), server_default='', nullable=True, comment='名称'),
    sa.Column('token', sa.String(length=80), nullable=True, comment='apikey'),
    sa.Column('token_type', sa.String(length=50), server_default='data_api', nullable=True, comment='用途 data_api/agent/...'),
    sa.Column('ref_id', sa.String(length=200), nullable=True, comment='绑定的资源(如数据模型 code);空=该 type 全部'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='1启用 0停用'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='过期时间(空=永不)'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='通用 API Token 表'
    )
    op.create_index(op.f('ix_api_token_tenant_id'), 'api_token', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_token_token'), 'api_token', ['token'], unique=False)
    op.create_table('dag_graph',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('dag_task_id', sa.String(length=36), nullable=True, comment='所属 DAG 任务id'),
    sa.Column('version', sa.String(length=64), server_default='draft', nullable=True, comment="版本:'draft' 或 发布版本号"),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=True, comment='draft/published/archived'),
    sa.Column('graph', sa.Text(), nullable=True, comment='整张图 JSON(nodes/edges/viewport)'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='发布说明'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='DAG 图版本文档表'
    )
    op.create_index(op.f('ix_dag_graph_dag_task_id'), 'dag_graph', ['dag_task_id'], unique=False)
    op.create_index(op.f('ix_dag_graph_tenant_id'), 'dag_graph', ['tenant_id'], unique=False)
    op.create_table('data_model',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=200), server_default='', nullable=True, comment='名称'),
    sa.Column('code', sa.String(length=200), server_default='', nullable=True, comment='编码'),
    sa.Column('datasource_code', sa.String(length=200), nullable=True, comment='引用的数据源编码'),
    sa.Column('kind', sa.String(length=50), server_default='table', nullable=True, comment='table/collection/index/topic/custom_query'),
    sa.Column('object_name', sa.String(length=200), nullable=True, comment='表/索引/集合名'),
    sa.Column('db_schema', sa.String(length=200), server_default='', nullable=True, comment='schema/库名'),
    sa.Column('fields', sa.JSON(), nullable=True, comment='字段结构(introspect 缓存)'),
    sa.Column('default_filters', sa.JSON(), nullable=True, comment='默认过滤条件'),
    sa.Column('auth', sa.String(length=200), server_default='query,extract', nullable=True, comment='授权位 query/extract/api/write(逗号)'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态 1启用 0停用'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据模型表'
    )
    op.create_index(op.f('ix_data_model_tenant_id'), 'data_model', ['tenant_id'], unique=False)
    op.create_table('data_source',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=200), server_default='', nullable=True, comment='名称'),
    sa.Column('code', sa.String(length=200), server_default='', nullable=True, comment='编码(稳定引用)'),
    sa.Column('source_type', sa.String(length=50), nullable=True, comment='源类型,如 mysql/elasticsearch'),
    sa.Column('family', sa.String(length=50), nullable=True, comment='源族,如 rdbms/search/vector'),
    sa.Column('config', sa.JSON(), nullable=True, comment='非密钥连接参数(JSON)'),
    sa.Column('secrets', sa.Text(), nullable=True, comment='密钥(AES 加密)'),
    sa.Column('status', sa.String(length=20), server_default='untested', nullable=True, comment='状态 untested/ok/failed'),
    sa.Column('last_test_at', sa.DateTime(), nullable=True, comment='最后测试时间'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据源表'
    )
    op.create_index(op.f('ix_data_source_tenant_id'), 'data_source', ['tenant_id'], unique=False)
    op.create_table('gen_table',
    sa.Column('table_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('table_name', sa.String(length=200), server_default='', nullable=True, comment='表名称'),
    sa.Column('table_comment', sa.String(length=500), server_default='', nullable=True, comment='表描述'),
    sa.Column('sub_table_name', sa.String(length=64), nullable=True, comment='关联子表的表名'),
    sa.Column('sub_table_fk_name', sa.String(length=64), nullable=True, comment='子表关联的外键名'),
    sa.Column('class_name', sa.String(length=100), server_default='', nullable=True, comment='实体类名称'),
    sa.Column('tpl_category', sa.String(length=200), server_default='crud', nullable=True, comment='使用的模板（crud单表操作 tree树表操作）'),
    sa.Column('tpl_web_type', sa.String(length=30), server_default='', nullable=True, comment='前端模板类型（element-ui模版 element-plus模版）'),
    sa.Column('package_name', sa.String(length=100), nullable=True, comment='生成包路径'),
    sa.Column('module_name', sa.String(length=30), nullable=True, comment='生成模块名'),
    sa.Column('business_name', sa.String(length=30), nullable=True, comment='生成业务名'),
    sa.Column('function_name', sa.String(length=50), nullable=True, comment='生成功能名'),
    sa.Column('function_author', sa.String(length=50), nullable=True, comment='生成功能作者'),
    sa.Column('gen_type', sa.CHAR(length=1), server_default='0', nullable=True, comment='生成代码方式（0zip压缩包 1自定义路径）'),
    sa.Column('gen_path', sa.String(length=200), server_default='/', nullable=True, comment='生成路径（不填默认项目路径）'),
    sa.Column('options', sa.String(length=1000), nullable=True, comment='其它生成选项'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('table_id'),
    comment='代码生成业务表'
    )
    op.create_table('gen_table_column',
    sa.Column('column_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('table_id', sa.BigInteger(), nullable=True, comment='归属表编号'),
    sa.Column('column_name', sa.String(length=200), nullable=True, comment='列名称'),
    sa.Column('column_comment', sa.String(length=500), nullable=True, comment='列描述'),
    sa.Column('column_type', sa.String(length=100), nullable=True, comment='列类型'),
    sa.Column('python_type', sa.String(length=500), nullable=True, comment='PYTHON类型'),
    sa.Column('python_field', sa.String(length=200), nullable=True, comment='PYTHON字段名'),
    sa.Column('is_pk', sa.CHAR(length=1), nullable=True, comment='是否主键（1是）'),
    sa.Column('is_increment', sa.CHAR(length=1), nullable=True, comment='是否自增（1是）'),
    sa.Column('is_required', sa.CHAR(length=1), nullable=True, comment='是否必填（1是）'),
    sa.Column('is_unique', sa.CHAR(length=1), nullable=True, comment='是否唯一（1是）'),
    sa.Column('is_insert', sa.CHAR(length=1), nullable=True, comment='是否为插入字段（1是）'),
    sa.Column('is_edit', sa.CHAR(length=1), nullable=True, comment='是否编辑字段（1是）'),
    sa.Column('is_list', sa.CHAR(length=1), nullable=True, comment='是否列表字段（1是）'),
    sa.Column('is_query', sa.CHAR(length=1), nullable=True, comment='是否查询字段（1是）'),
    sa.Column('query_type', sa.String(length=200), server_default='EQ', nullable=True, comment='查询方式（等于、不等于、大于、小于、范围）'),
    sa.Column('html_type', sa.String(length=200), nullable=True, comment='显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）'),
    sa.Column('dict_type', sa.String(length=200), server_default='', nullable=True, comment='字典类型'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('column_id'),
    comment='代码生成业务表字段'
    )
    op.create_table('rag_chunk',
    sa.Column('id', sa.String(length=36), nullable=False, comment='分段ID(=向量库_id)'),
    sa.Column('dataset_id', sa.String(length=36), nullable=False, comment='所属知识库'),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='所属文档'),
    sa.Column('chunk_type', sa.String(length=10), server_default='chunk', nullable=True, comment='类型 chunk/qa'),
    sa.Column('content', sa.Text(), nullable=True, comment='正文'),
    sa.Column('question', sa.Text(), nullable=True, comment='问题(QA)'),
    sa.Column('question_hash', sa.String(length=64), nullable=True, comment='问题hash(QA精确命中)'),
    sa.Column('answer', sa.Text(), nullable=True, comment='答案(QA)'),
    sa.Column('hash', sa.String(length=64), nullable=True, comment='正文hash(去重)'),
    sa.Column('position', sa.Integer(), server_default='0', nullable=True, comment='序号'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态 1已索引0未索引'),
    sa.Column('star_flag', sa.SmallInteger(), server_default='0', nullable=True, comment='标星'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='RAG 分段'
    )
    op.create_index(op.f('ix_rag_chunk_dataset_id'), 'rag_chunk', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_rag_chunk_document_id'), 'rag_chunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_chunk_question_hash'), 'rag_chunk', ['question_hash'], unique=False)
    op.create_index(op.f('ix_rag_chunk_tenant_id'), 'rag_chunk', ['tenant_id'], unique=False)
    op.create_table('rag_dataset',
    sa.Column('id', sa.String(length=36), nullable=False, comment='知识库ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('source_id', sa.String(length=36), nullable=True, comment='专属数据源ID(空=普通知识库)'),
    sa.Column('embedding_provider', sa.String(length=50), nullable=True, comment='embedding 提供商'),
    sa.Column('embedding_model', sa.String(length=100), nullable=True, comment='embedding 模型编码'),
    sa.Column('embedding_dims', sa.Integer(), nullable=True, comment='向量维度'),
    sa.Column('vector_backend', sa.String(length=50), server_default='elasticsearch', nullable=True, comment='向量后端'),
    sa.Column('vector_source_id', sa.String(length=36), nullable=True, comment='向量库 data_source(空=用系统默认ES)'),
    sa.Column('index_name', sa.String(length=200), nullable=True, comment='向量索引/集合名'),
    sa.Column('retrieval_config', sa.Text(), nullable=True, comment='默认检索参数(JSON)'),
    sa.Column('built_in', sa.SmallInteger(), server_default='0', nullable=True, comment='是否内置'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态 1启用0禁用'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='RAG 知识库'
    )
    op.create_index(op.f('ix_rag_dataset_source_id'), 'rag_dataset', ['source_id'], unique=False)
    op.create_index(op.f('ix_rag_dataset_tenant_id'), 'rag_dataset', ['tenant_id'], unique=False)
    op.create_table('rag_document',
    sa.Column('id', sa.String(length=36), nullable=False, comment='文档ID'),
    sa.Column('dataset_id', sa.String(length=36), nullable=False, comment='所属知识库'),
    sa.Column('name', sa.String(length=300), nullable=False, comment='文档名'),
    sa.Column('document_type', sa.String(length=30), server_default='upload_file', nullable=True, comment='来源类型 upload_file/website/text/datamodel'),
    sa.Column('file_key', sa.String(length=500), nullable=True, comment='文件存储 key'),
    sa.Column('source', sa.String(length=1000), nullable=True, comment='来源(URL / datamodel_id 等)'),
    sa.Column('meta_data', sa.Text(), nullable=True, comment='元数据(JSON)'),
    sa.Column('chunk_strategy', sa.Text(), nullable=True, comment='切分/清洗策略(JSON)'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='原文hash(增量,未变则跳过重训)'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态 1待训练2训练中3成功4失败'),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=True, comment='分段数'),
    sa.Column('error', sa.String(length=1000), nullable=True, comment='失败原因'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='RAG 文档'
    )
    op.create_index(op.f('ix_rag_document_dataset_id'), 'rag_document', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_rag_document_tenant_id'), 'rag_document', ['tenant_id'], unique=False)
    op.create_table('rag_embedding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('hash', sa.String(length=64), nullable=False, comment='文本hash(md5)'),
    sa.Column('model_id', sa.String(length=150), nullable=False, comment='provider:model'),
    sa.Column('dim', sa.Integer(), nullable=True, comment='维度'),
    sa.Column('vector', sa.Text(), nullable=True, comment='向量(JSON数组)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='RAG embedding 缓存'
    )
    op.create_index(op.f('ix_rag_embedding_hash'), 'rag_embedding', ['hash'], unique=False)
    op.create_table('sys_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False, comment='参数主键'),
    sa.Column('config_name', sa.String(length=100), server_default='', nullable=True, comment='参数名称'),
    sa.Column('config_key', sa.String(length=100), server_default='', nullable=True, comment='参数键名'),
    sa.Column('config_value', sa.String(length=500), server_default='', nullable=True, comment='参数键值'),
    sa.Column('config_type', sa.CHAR(length=1), server_default='N', nullable=True, comment='系统内置（Y是 N否）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('config_id'),
    comment='参数配置表'
    )
    op.create_table('sys_dept',
    sa.Column('dept_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='部门id'),
    sa.Column('parent_id', sa.BigInteger(), server_default='0', nullable=True, comment='父部门id'),
    sa.Column('ancestors', sa.String(length=50), server_default='', nullable=True, comment='祖级列表'),
    sa.Column('dept_name', sa.String(length=30), server_default='', nullable=True, comment='部门名称'),
    sa.Column('order_num', sa.Integer(), server_default='0', nullable=True, comment='显示顺序'),
    sa.Column('leader', sa.String(length=20), nullable=True, comment='负责人'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='部门状态（0正常 1停用）'),
    sa.Column('del_flag', sa.CHAR(length=1), server_default='0', nullable=True, comment='删除标志（0代表存在 2代表删除）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('dept_id'),
    comment='部门表'
    )
    op.create_index(op.f('ix_sys_dept_tenant_id'), 'sys_dept', ['tenant_id'], unique=False)
    op.create_table('sys_dict_data',
    sa.Column('dict_code', sa.BigInteger(), autoincrement=True, nullable=False, comment='字典编码'),
    sa.Column('dict_sort', sa.Integer(), server_default='0', nullable=True, comment='字典排序'),
    sa.Column('dict_label', sa.String(length=100), server_default='', nullable=True, comment='字典标签'),
    sa.Column('dict_value', sa.String(length=100), server_default='', nullable=True, comment='字典键值'),
    sa.Column('dict_type', sa.String(length=100), server_default='', nullable=True, comment='字典类型'),
    sa.Column('css_class', sa.String(length=100), nullable=True, comment='样式属性（其他样式扩展）'),
    sa.Column('list_class', sa.String(length=100), nullable=True, comment='表格回显样式'),
    sa.Column('is_default', sa.CHAR(length=1), server_default='N', nullable=True, comment='是否默认（Y是 N否）'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='状态（0正常 1停用）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('dict_code'),
    comment='字典数据表'
    )
    op.create_table('sys_dict_type',
    sa.Column('dict_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='字典主键'),
    sa.Column('dict_name', sa.String(length=100), server_default='', nullable=True, comment='字典名称'),
    sa.Column('dict_type', sa.String(length=100), server_default='', nullable=True, comment='字典类型'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='状态（0正常 1停用）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('dict_id'),
    sa.UniqueConstraint('dict_type'),
    comment='字典类型表'
    )
    op.create_table('sys_job',
    sa.Column('job_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='任务ID'),
    sa.Column('job_name', sa.String(length=64), server_default='', nullable=False, comment='任务名称'),
    sa.Column('job_group', sa.String(length=64), server_default='default', nullable=False, comment='任务组名'),
    sa.Column('job_executor', sa.String(length=64), server_default='default', nullable=True, comment='任务执行器'),
    sa.Column('invoke_target', sa.String(length=500), nullable=False, comment='调用目标字符串'),
    sa.Column('job_args', sa.String(length=255), server_default='', nullable=True, comment='位置参数'),
    sa.Column('job_kwargs', sa.String(length=255), server_default='', nullable=True, comment='关键字参数'),
    sa.Column('cron_expression', sa.String(length=255), server_default='', nullable=True, comment='cron执行表达式'),
    sa.Column('misfire_policy', sa.String(length=20), server_default='3', nullable=True, comment='计划执行错误策略（1立即执行 2执行一次 3放弃执行）'),
    sa.Column('concurrent', sa.CHAR(length=1), server_default='1', nullable=True, comment='是否并发执行（0允许 1禁止）'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='状态（0正常 1暂停）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注信息'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('job_id', 'job_name', 'job_group'),
    comment='定时任务调度表'
    )
    op.create_index(op.f('ix_sys_job_tenant_id'), 'sys_job', ['tenant_id'], unique=False)
    op.create_table('sys_job_log',
    sa.Column('job_log_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='任务日志ID'),
    sa.Column('job_name', sa.String(length=64), nullable=False, comment='任务名称'),
    sa.Column('job_group', sa.String(length=64), nullable=False, comment='任务组名'),
    sa.Column('job_executor', sa.String(length=64), nullable=False, comment='任务执行器'),
    sa.Column('invoke_target', sa.String(length=500), nullable=False, comment='调用目标字符串'),
    sa.Column('job_args', sa.String(length=255), server_default='', nullable=True, comment='位置参数'),
    sa.Column('job_kwargs', sa.String(length=255), server_default='', nullable=True, comment='关键字参数'),
    sa.Column('job_trigger', sa.String(length=255), server_default='', nullable=True, comment='任务触发器'),
    sa.Column('job_message', sa.String(length=500), nullable=True, comment='日志信息'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='执行状态（0正常 1失败）'),
    sa.Column('exception_info', sa.String(length=2000), server_default='', nullable=True, comment='异常信息'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('job_log_id'),
    comment='定时任务调度日志表'
    )
    op.create_table('sys_logininfor',
    sa.Column('info_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='访问ID'),
    sa.Column('user_name', sa.String(length=50), server_default='', nullable=True, comment='用户账号'),
    sa.Column('ipaddr', sa.String(length=128), server_default='', nullable=True, comment='登录IP地址'),
    sa.Column('login_location', sa.String(length=255), server_default='', nullable=True, comment='登录地点'),
    sa.Column('browser', sa.String(length=50), server_default='', nullable=True, comment='浏览器类型'),
    sa.Column('os', sa.String(length=50), server_default='', nullable=True, comment='操作系统'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='登录状态（0成功 1失败）'),
    sa.Column('msg', sa.String(length=255), server_default='', nullable=True, comment='提示消息'),
    sa.Column('login_time', sa.DateTime(), nullable=True, comment='访问时间'),
    sa.PrimaryKeyConstraint('info_id'),
    comment='系统访问记录'
    )
    op.create_index('idx_sys_logininfor_lt', 'sys_logininfor', ['login_time'], unique=False)
    op.create_index('idx_sys_logininfor_s', 'sys_logininfor', ['status'], unique=False)
    op.create_table('sys_menu',
    sa.Column('menu_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='菜单ID'),
    sa.Column('menu_name', sa.String(length=50), nullable=False, comment='菜单名称'),
    sa.Column('parent_id', sa.BigInteger(), server_default='0', nullable=True, comment='父菜单ID'),
    sa.Column('order_num', sa.Integer(), server_default='0', nullable=True, comment='显示顺序'),
    sa.Column('path', sa.String(length=200), server_default='', nullable=True, comment='路由地址'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='组件路径'),
    sa.Column('query', sa.String(length=255), nullable=True, comment='路由参数'),
    sa.Column('route_name', sa.String(length=50), server_default='', nullable=True, comment='路由名称'),
    sa.Column('is_frame', sa.Integer(), server_default='1', nullable=True, comment='是否为外链（0是 1否）'),
    sa.Column('is_cache', sa.Integer(), server_default='0', nullable=True, comment='是否缓存（0缓存 1不缓存）'),
    sa.Column('menu_type', sa.CHAR(length=1), server_default='', nullable=True, comment='菜单类型（M目录 C菜单 F按钮）'),
    sa.Column('visible', sa.CHAR(length=1), server_default='0', nullable=True, comment='菜单状态（0显示 1隐藏）'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='菜单状态（0正常 1停用）'),
    sa.Column('perms', sa.String(length=100), nullable=True, comment='权限标识'),
    sa.Column('icon', sa.String(length=100), server_default='#', nullable=True, comment='菜单图标'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('menu_id'),
    comment='菜单权限表'
    )
    op.create_table('sys_notice',
    sa.Column('notice_id', sa.Integer(), autoincrement=True, nullable=False, comment='公告ID'),
    sa.Column('notice_title', sa.String(length=50), nullable=False, comment='公告标题'),
    sa.Column('notice_type', sa.CHAR(length=1), nullable=False, comment='公告类型（1通知 2公告）'),
    sa.Column('notice_content', mysql.LONGBLOB(), nullable=True, comment='公告内容'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='公告状态（0正常 1关闭）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('notice_id'),
    comment='通知公告表'
    )
    op.create_index(op.f('ix_sys_notice_tenant_id'), 'sys_notice', ['tenant_id'], unique=False)
    op.create_table('sys_oper_log',
    sa.Column('oper_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='日志主键'),
    sa.Column('title', sa.String(length=50), server_default='', nullable=True, comment='模块标题'),
    sa.Column('business_type', sa.Integer(), server_default='0', nullable=True, comment='业务类型（0其它 1新增 2修改 3删除）'),
    sa.Column('method', sa.String(length=100), server_default='', nullable=True, comment='方法名称'),
    sa.Column('request_method', sa.String(length=10), server_default='', nullable=True, comment='请求方式'),
    sa.Column('operator_type', sa.Integer(), server_default='0', nullable=True, comment='操作类别（0其它 1后台用户 2手机端用户）'),
    sa.Column('oper_name', sa.String(length=50), server_default='', nullable=True, comment='操作人员'),
    sa.Column('dept_name', sa.String(length=50), server_default='', nullable=True, comment='部门名称'),
    sa.Column('oper_url', sa.String(length=255), server_default='', nullable=True, comment='请求URL'),
    sa.Column('oper_ip', sa.String(length=128), server_default='', nullable=True, comment='主机地址'),
    sa.Column('oper_location', sa.String(length=255), server_default='', nullable=True, comment='操作地点'),
    sa.Column('oper_param', sa.String(length=2000), server_default='', nullable=True, comment='请求参数'),
    sa.Column('json_result', sa.String(length=2000), server_default='', nullable=True, comment='返回参数'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True, comment='操作状态（0正常 1异常）'),
    sa.Column('error_msg', sa.String(length=2000), server_default='', nullable=True, comment='错误消息'),
    sa.Column('oper_time', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.Column('cost_time', sa.BigInteger(), server_default='0', nullable=True, comment='消耗时间'),
    sa.PrimaryKeyConstraint('oper_id'),
    comment='操作日志记录'
    )
    op.create_index('idx_sys_oper_log_bt', 'sys_oper_log', ['business_type'], unique=False)
    op.create_index('idx_sys_oper_log_ot', 'sys_oper_log', ['oper_time'], unique=False)
    op.create_index('idx_sys_oper_log_s', 'sys_oper_log', ['status'], unique=False)
    op.create_table('sys_post',
    sa.Column('post_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='岗位ID'),
    sa.Column('post_code', sa.String(length=64), nullable=False, comment='岗位编码'),
    sa.Column('post_name', sa.String(length=50), nullable=False, comment='岗位名称'),
    sa.Column('post_sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('status', sa.CHAR(length=1), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('post_id'),
    comment='岗位信息表'
    )
    op.create_table('sys_role',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('role_name', sa.String(length=30), nullable=False, comment='角色名称'),
    sa.Column('role_key', sa.String(length=100), nullable=False, comment='角色权限字符串'),
    sa.Column('role_sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('data_scope', sa.CHAR(length=1), server_default='1', nullable=True, comment='数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）'),
    sa.Column('menu_check_strictly', mysql.TINYINT(display_width=1), server_default='1', nullable=True, comment='菜单树选择项是否关联显示'),
    sa.Column('dept_check_strictly', mysql.TINYINT(display_width=1), server_default='1', nullable=True, comment='部门树选择项是否关联显示'),
    sa.Column('status', sa.CHAR(length=1), nullable=False, comment='角色状态（0正常 1停用）'),
    sa.Column('del_flag', sa.CHAR(length=1), server_default='0', nullable=True, comment='删除标志（0代表存在 2代表删除）'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('role_id'),
    comment='角色信息表'
    )
    op.create_table('sys_role_dept',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('dept_id', sa.BigInteger(), nullable=False, comment='部门ID'),
    sa.PrimaryKeyConstraint('role_id', 'dept_id'),
    comment='角色和部门关联表'
    )
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单ID'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id'),
    comment='角色和菜单关联表'
    )
    op.create_table('sys_user',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门ID'),
    sa.Column('user_name', sa.String(length=30), nullable=False, comment='用户账号'),
    sa.Column('nick_name', sa.String(length=30), nullable=False, comment='用户昵称'),
    sa.Column('user_type', sa.String(length=2), server_default='00', nullable=True, comment='用户类型（00系统用户）'),
    sa.Column('email', sa.String(length=50), server_default='', nullable=True, comment='用户邮箱'),
    sa.Column('phonenumber', sa.String(length=11), server_default='', nullable=True, comment='手机号码'),
    sa.Column('sex', sa.CHAR(length=1), server_default='0', nullable=True, comment='用户性别（0男 1女 2未知）'),
    sa.Column('avatar', sa.String(length=100), server_default='', nullable=True, comment='头像地址'),
    sa.Column('password', sa.String(length=100), server_default='', nullable=True, comment='密码'),
    sa.Column('status', sa.CHAR(length=1), server_default='0', nullable=True, comment='帐号状态（0正常 1停用）'),
    sa.Column('del_flag', sa.CHAR(length=1), server_default='0', nullable=True, comment='删除标志（0代表存在 2代表删除）'),
    sa.Column('login_ip', sa.String(length=128), server_default='', nullable=True, comment='最后登录IP'),
    sa.Column('login_date', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('pwd_update_date', sa.DateTime(), nullable=True, comment='密码最后更新时间'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='用户信息表'
    )
    op.create_index(op.f('ix_sys_user_tenant_id'), 'sys_user', ['tenant_id'], unique=False)
    op.create_table('sys_user_oauth',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='平台用户ID'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='身份提供商:github/...'),
    sa.Column('open_id', sa.String(length=255), nullable=False, comment='提供商内用户唯一ID'),
    sa.Column('union_id', sa.String(length=255), nullable=True, comment='跨应用统一ID(可选)'),
    sa.Column('login_name', sa.String(length=100), nullable=True, comment='第三方登录名/昵称'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='第三方头像'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='绑定时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'open_id', name='uk_provider_openid'),
    comment='第三方身份绑定表(SSO)'
    )
    op.create_index(op.f('ix_sys_user_oauth_tenant_id'), 'sys_user_oauth', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_user_oauth_user_id'), 'sys_user_oauth', ['user_id'], unique=False)
    op.create_table('sys_user_post',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='岗位ID'),
    sa.PrimaryKeyConstraint('user_id', 'post_id'),
    comment='用户与岗位关联表'
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='用户和角色关联表'
    )
    op.create_table('sys_user_tenant',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID(顶级部门)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认激活租户'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='加入时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uk_user_tenant'),
    comment='用户-租户成员表(一人多租户)'
    )
    op.create_index(op.f('ix_sys_user_tenant_tenant_id'), 'sys_user_tenant', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_user_tenant_user_id'), 'sys_user_tenant', ['user_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('template_code', sa.String(length=200), server_default='', nullable=True, comment='任务模板编码'),
    sa.Column('task_type', sa.SmallInteger(), server_default='1', nullable=True, comment='任务类型，1普通任务2dag工作流任务'),
    sa.Column('run_type', sa.SmallInteger(), server_default='1', nullable=True, comment='DAG运行模式，1分布式2单机'),
    sa.Column('name', sa.String(length=100), server_default='', nullable=True, comment='名称'),
    sa.Column('params', sa.Text(), nullable=True, comment='参数'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=True, comment='状态 0停用 1启用'),
    sa.Column('built_in', sa.SmallInteger(), server_default='0', nullable=True, comment='是否内置 1是 0不是'),
    sa.Column('trigger_type', sa.SmallInteger(), server_default='1', nullable=True, comment='触发方式，1单次2定时'),
    sa.Column('crontab', sa.String(length=500), server_default='', nullable=True, comment='定时设置'),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=True, comment='优先级'),
    sa.Column('retry', sa.Integer(), server_default='0', nullable=True, comment='失败重试次数'),
    sa.Column('countdown', sa.Integer(), server_default='0', nullable=True, comment='失败重试间隔(秒)'),
    sa.Column('run_queue', sa.String(length=200), server_default='default', nullable=True, comment='运行队列'),
    sa.Column('running_id', sa.String(length=36), nullable=True, comment='正在运行任务实例ID'),
    sa.Column('job_id', sa.Integer(), nullable=True, comment='关联的调度任务ID(sys_job)'),
    sa.Column('published_version_id', sa.String(length=36), nullable=True, comment='DAG 当前生效的发布版(dag_graph.id)'),
    sa.Column('alert_strategy_ids', sa.String(length=500), server_default='', nullable=True, comment='绑定的告警策略ID(逗号分隔)'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务表'
    )
    op.create_index(op.f('ix_task_tenant_id'), 'task', ['tenant_id'], unique=False)
    op.create_table('task_instance',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键(celery task uuid)'),
    sa.Column('parent_id', sa.String(length=36), server_default='', nullable=True, comment='父任务id'),
    sa.Column('task_id', sa.String(length=36), server_default='', nullable=True, comment='任务id'),
    sa.Column('node_id', sa.String(length=36), server_default='', nullable=True, comment='dag节点id'),
    sa.Column('name', sa.String(length=100), server_default='', nullable=True, comment='任务名称'),
    sa.Column('status', sa.String(length=50), server_default='STARTED', nullable=True, comment='状态'),
    sa.Column('worker', sa.String(length=200), server_default='', nullable=True, comment='worker'),
    sa.Column('retry_num', sa.Integer(), server_default='0', nullable=True, comment='重试次数'),
    sa.Column('progress', sa.Float(), server_default='0', nullable=True, comment='任务进度'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('closed', sa.SmallInteger(), server_default='0', nullable=True, comment='是否已关闭'),
    sa.Column('result', sa.Text(), nullable=True, comment='执行结果'),
    sa.Column('dag_version_id', sa.String(length=36), nullable=True, comment='DAG run 跑的图版本(dag_graph.id)'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务实例表'
    )
    op.create_index(op.f('ix_task_instance_tenant_id'), 'task_instance', ['tenant_id'], unique=False)
    op.create_table('task_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('task_uuid', sa.String(length=36), server_default='', nullable=True, comment='任务实例ID'),
    sa.Column('level', sa.String(length=20), server_default='INFO', nullable=True, comment='日志级别'),
    sa.Column('content', sa.Text(), nullable=True, comment='日志内容'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID(顶级部门)'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务执行日志表'
    )
    op.create_index(op.f('ix_task_log_tenant_id'), 'task_log', ['tenant_id'], unique=False)
    op.create_table('task_template',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=200), server_default='', nullable=True, comment='模板名称'),
    sa.Column('code', sa.String(length=200), server_default='', nullable=True, comment='模板编码'),
    sa.Column('icon', sa.String(length=500), server_default='', nullable=True, comment='模板图标'),
    sa.Column('type', sa.SmallInteger(), server_default='1', nullable=True, comment='表单类型,1内置组件2动态配置'),
    sa.Column('runner_type', sa.SmallInteger(), server_default='1', nullable=True, comment='执行器类型，1内置执行器2动态代码'),
    sa.Column('runner_code', sa.Text(), nullable=True, comment='动态执行器代码'),
    sa.Column('component', sa.String(length=500), server_default='', nullable=True, comment='前端组件'),
    sa.Column('params', sa.Text(), nullable=True, comment='模板参数schema'),
    sa.Column('built_in', sa.SmallInteger(), server_default='0', nullable=True, comment='是否内置 1是 0不是'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态 1启用 0禁用'),
    sa.Column('create_by', sa.String(length=64), server_default='', nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), server_default='', nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), server_default='', nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务模板表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_template')
    op.drop_index(op.f('ix_task_log_tenant_id'), table_name='task_log')
    op.drop_table('task_log')
    op.drop_index(op.f('ix_task_instance_tenant_id'), table_name='task_instance')
    op.drop_table('task_instance')
    op.drop_index(op.f('ix_task_tenant_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_sys_user_tenant_user_id'), table_name='sys_user_tenant')
    op.drop_index(op.f('ix_sys_user_tenant_tenant_id'), table_name='sys_user_tenant')
    op.drop_table('sys_user_tenant')
    op.drop_table('sys_user_role')
    op.drop_table('sys_user_post')
    op.drop_index(op.f('ix_sys_user_oauth_user_id'), table_name='sys_user_oauth')
    op.drop_index(op.f('ix_sys_user_oauth_tenant_id'), table_name='sys_user_oauth')
    op.drop_table('sys_user_oauth')
    op.drop_index(op.f('ix_sys_user_tenant_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role_menu')
    op.drop_table('sys_role_dept')
    op.drop_table('sys_role')
    op.drop_table('sys_post')
    op.drop_index('idx_sys_oper_log_s', table_name='sys_oper_log')
    op.drop_index('idx_sys_oper_log_ot', table_name='sys_oper_log')
    op.drop_index('idx_sys_oper_log_bt', table_name='sys_oper_log')
    op.drop_table('sys_oper_log')
    op.drop_index(op.f('ix_sys_notice_tenant_id'), table_name='sys_notice')
    op.drop_table('sys_notice')
    op.drop_table('sys_menu')
    op.drop_index('idx_sys_logininfor_s', table_name='sys_logininfor')
    op.drop_index('idx_sys_logininfor_lt', table_name='sys_logininfor')
    op.drop_table('sys_logininfor')
    op.drop_table('sys_job_log')
    op.drop_index(op.f('ix_sys_job_tenant_id'), table_name='sys_job')
    op.drop_table('sys_job')
    op.drop_table('sys_dict_type')
    op.drop_table('sys_dict_data')
    op.drop_index(op.f('ix_sys_dept_tenant_id'), table_name='sys_dept')
    op.drop_table('sys_dept')
    op.drop_table('sys_config')
    op.drop_index(op.f('ix_rag_embedding_hash'), table_name='rag_embedding')
    op.drop_table('rag_embedding')
    op.drop_index(op.f('ix_rag_document_tenant_id'), table_name='rag_document')
    op.drop_index(op.f('ix_rag_document_dataset_id'), table_name='rag_document')
    op.drop_table('rag_document')
    op.drop_index(op.f('ix_rag_dataset_tenant_id'), table_name='rag_dataset')
    op.drop_index(op.f('ix_rag_dataset_source_id'), table_name='rag_dataset')
    op.drop_table('rag_dataset')
    op.drop_index(op.f('ix_rag_chunk_tenant_id'), table_name='rag_chunk')
    op.drop_index(op.f('ix_rag_chunk_question_hash'), table_name='rag_chunk')
    op.drop_index(op.f('ix_rag_chunk_document_id'), table_name='rag_chunk')
    op.drop_index(op.f('ix_rag_chunk_dataset_id'), table_name='rag_chunk')
    op.drop_table('rag_chunk')
    op.drop_table('gen_table_column')
    op.drop_table('gen_table')
    op.drop_index(op.f('ix_data_source_tenant_id'), table_name='data_source')
    op.drop_table('data_source')
    op.drop_index(op.f('ix_data_model_tenant_id'), table_name='data_model')
    op.drop_table('data_model')
    op.drop_index(op.f('ix_dag_graph_tenant_id'), table_name='dag_graph')
    op.drop_index(op.f('ix_dag_graph_dag_task_id'), table_name='dag_graph')
    op.drop_table('dag_graph')
    op.drop_index(op.f('ix_api_token_token'), table_name='api_token')
    op.drop_index(op.f('ix_api_token_tenant_id'), table_name='api_token')
    op.drop_table('api_token')
    op.drop_index(op.f('ix_alert_strategy_tenant_id'), table_name='alert_strategy')
    op.drop_table('alert_strategy')
    op.drop_index(op.f('ix_alert_record_tenant_id'), table_name='alert_record')
    op.drop_table('alert_record')
    op.drop_index(op.f('ix_ai_tool_tenant_id'), table_name='ai_tool')
    op.drop_table('ai_tool')
    op.drop_index(op.f('ix_ai_models_tenant_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_ai_chat_config_tenant_id'), table_name='ai_chat_config')
    op.drop_table('ai_chat_config')
    op.drop_index(op.f('ix_ai_app_tenant_id'), table_name='ai_app')
    op.drop_table('ai_app')
    # ### end Alembic commands ###
