apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ezdata.fullname" . }}-env
  namespace: ezdata-helm
data:
  prod.env: |-
    # 数据库相关配置
    DB_TYPE=mysql
    DB_CHARSET=utf8mb4
    POOL_RECYCLE=600
    ECHO_SQL=0
    {{- if .Values.externalDatabase.enabled }}
    DB_HOST={{.Values.externalDatabase.host}}
    DB_PORT={{.Values.externalDatabase.port}}
    DB_USER={{.Values.externalDatabase.username}}
    DB_PWD={{.Values.externalDatabase.password}}
    DB_NAME={{.Values.externalDatabase.database}}
    {{- end }}
    {{- if .Values.mysql.enabled }}
    DB_HOST={{.Values.mysql.primary.service.clusterIP}}
    DB_PORT=3306
    DB_USER={{.Values.mysql.auth.username}}
    DB_PWD={{.Values.mysql.auth.password}}
    DB_NAME={{.Values.mysql.auth.database}}
    {{- end }}
    # worker相关配置
    WORKER_TYPE=celery
    # redis 相关配置
    {{- if .Values.externalRedis.enabled }}
    REDIS_HOST={{.Values.externalRedis.host}}
    REDIS_PORT={{.Values.externalRedis.port}}
    REDIS_PWD={{.Values.externalRedis.password}}
    REDIS_DB={{.Values.externalRedis.db}}
    {{- end }}
    {{- if .Values.redis.enabled }}
    REDIS_HOST={{.Values.redis.master.service.clusterIP}}
    REDIS_PORT=6379
    REDIS_PWD={{.Values.redis.auth.password}}
    REDIS_DB={{.Values.redis.auth.db}}
    {{- end }}
    # celery 配置
    CELERY_DEFAULT_QUEUE=default
    FLOWER_API_URL=http://{{.Values.scheduler.service.clusterIP}}:5555
    SCHEDULER_API_URL=http://{{.Values.scheduler.service.clusterIP}}:8002/api/scheduler
    # 对象存储相关配置
    OSS_TYPE=minio
    {{- if .Values.externalMinio.enabled }}
    OSS_HOST={{.Values.externalMinio.host}}
    OSS_PORT={{.Values.externalMinio.port}}
    OSS_KEY={{.Values.externalMinio.username}}
    OSS_SECRET={{.Values.externalMinio.password}}
    OSS_BUCKET={{.Values.externalMinio.bucket}}
    {{- end }}
    {{- if .Values.minio.enabled }}
    OSS_HOST={{.Values.minio.service.clusterIP}}
    OSS_PORT=9000
    OSS_KEY={{.Values.minio.auth.rootUser}}
    OSS_SECRET={{.Values.minio.auth.rootPassword}}
    OSS_BUCKET={{.Values.minio.defaultBuckets}}
    {{- end }}
    # 日志相关配置
    LOGGER_TYPE=es
    LOG_LEVEL=INFO
    SYS_LOG_INDEX=sys_logs
    TASK_LOG_INDEX=task_logs
    INTERFACE_LOG_INDEX=interface_logs
    # 若日志模式为es  elasticsearch相关配置
    {{- if .Values.externalElasticSearch.enabled }}
    ES_HOSTS={{.Values.externalElasticSearch.hosts}}
    ES_USER={{.Values.externalElasticSearch.username}}
    ES_PWD={{.Values.externalElasticSearch.password}}
    {{- end }}
    {{- if .Values.elasticsearch.enabled }}
    ES_HOSTS={{.Values.elasticsearch.service.clusterIP}}:9200
    ES_USER=
    ES_PWD=
    {{- end }}
    # web相关配置
    # 是否启用token刷新机制
    USE_TOKEN_REFRESH=0
    # 用户token过期时间
    TOKEN_EXP_TIME=86400
    # 服务私钥
    SECRET_KEY='erwqefdscweer)qidq1'
    # xorbits集群地址 local为本地
    XORBITS_CLUSTER=local