apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ezdata.fullname" . }}-worker
  namespace: {{ include "ezdata.name" . }}
  labels:
    app: {{ include "ezdata.name" . }}-worker
    app.kubernetes.io/name: {{ include "ezdata.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "ezdata.name" . }}-worker
      app.kubernetes.io/name: {{ include "ezdata.name" . }}
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: {{ include "ezdata.name" . }}-worker
        app.kubernetes.io/name: {{ include "ezdata.name" . }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        version: {{ .Chart.Version }}
    spec:
      volumes:
        - name: {{ include "ezdata.fullname" . }}-env
          configMap:
            name: {{ template "ezdata.fullname" . }}-env
            items:
              - key: prod.env
                path: prod.env
      containers:
        - name: container-ezdata
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/sh
            - "-c"
            - bash init.sh
          workingDir: //opt/ezdata
          ports:
            - name: http-9001
              containerPort: 9001
              protocol: TCP
          env:
            - name: read_env
              value: "{{ .Values.worker.env.read_env }}"
            - name: ENV
              value: "{{ .Values.worker.env.ENV }}"
            - name: run_upgrade
              value: "{{ .Values.worker.env.run_upgrade }}"
            - name: upgrade_packages
              value: "{{ .Values.api.env.upgrade_packages }}"
            - name: run_web
              value: "{{ .Values.worker.env.run_web }}"
            - name: web_worker
              value: "{{ .Values.worker.env.web_worker }}"
            - name: run_scheduler
              value: "{{ .Values.worker.env.run_scheduler }}"
            - name: run_flower
              value: "{{ .Values.worker.env.run_flower }}"
            - name: run_worker
              value: "{{ .Values.worker.env.run_worker }}"
            - name: worker_concurrency
              value: "{{ .Values.worker.env.worker_concurrency }}"
            - name: worker_queue
              value: "{{ .Values.worker.env.worker_queue }}"
            - name: worker_process
              value: "{{ .Values.worker.env.worker_process }}"
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: {{ include "ezdata.fullname" . }}-env
              readOnly: true
              mountPath: /opt/ezdata/prod.env
              subPath: prod.env
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
