apiVersion: v1
kind: Service
metadata:
  name: {{ include "ezdata.fullname" . }}-api
  namespace: {{ include "ezdata.name" . }}
  labels:
    app: {{ include "ezdata.name" . }}-api
    app.kubernetes.io/name: {{ include "ezdata.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    version: {{ .Chart.Version }}
  annotations:
    servicemesh.kubesphere.io/enabled: "false"
spec:
  ports:
    - name: api
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: {{ .Values.api.service.nodePort.api }}
  selector:
    app: {{ include "ezdata.name" . }}-api
    app.kubernetes.io/name: {{ include "ezdata.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  clusterIP: {{ .Values.api.service.clusterIP }}
  clusterIPs:
    - {{ .Values.api.service.clusterIP }}
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster